### PR TITLE
Fixed model flattening generating no fzn and ozn file

### LINKED ISSUE #29: Model Flattening generates no fzn and ozn file
Hi,
when I try running any model, for instance the 'knapsack' model, I get the error " 'NoneType' object has no attribute 'endswith' " which appears for the mzn_file variable in the args function being called from the _solve function.
I could backtrack the problem to the mzn2fzn function where the process is run but during that no fzn or ozn file is generated. This leads to the fzn_file and ozn_file variables being assigned the None object which then is handed over to the _solve function and causing the problem.

Has anyone ever had the same problem or knows how to deal with it?
Best regards,
Julian

### PR DESCRIPTION
**Pull request by madsmtm**
`_solve` (Or rather, the functions that `_solve` calls further down the execution chain) expects its `mzn_file` parameter to be strings, but `None` may be returned as `fzn_file` from `mzn2fzn`

I'm not familiar with the rest of the code structure, so this may not be the best place to implement this fix

Fixed #29

### CODE REVIEW

**Comment by paolodragone** [comment]
Hi @madsmtm! thank you for your contribution!
I'll hold on to this pull request until I figure out why the mzn2fzn call is returning None, which started happening with MiniZinc version 2.2.0. The last version of MiniZinc that PyMzn works fine with is the 2.1.7, so you can use that in the meantime if you don't need the newest features. Cheers!
